/*
 * networkmanager.h
 *
 */
#include <common/smsgdef.h>

#ifndef NETWORK_NETWORKMANAGER_H_
#define NETWORK_NETWORKMANAGER_H_

#define SMSG_WIFI_OK					0x00000001 // Wifi OK
#define SMSG_WIFI_ERROR					0x00000002 // Wifi Error
#define SMSG_WIFI_FAIL					0x00000004 // Wifi Fail
#define SMSG_WIFI_TIMEOUT				0x00000008 // Wifi Timeout
#define SMSG_GET_TCP_STATUS				0x00000010 // Get TCP Status
#define SMSG_READY_TO_SEND				0x00000020 // Ready to Send
#define SMSG_SEND_OK					0x00000040 // Send OK
#define SMSG_SEND_FAIL					0x00000080 // Send FAIL
#define SMSG_SEND_DATA					0x00000100 // Send Data
#define SMSG_RECEIVE_ACK				0x00000200 // Receive Ack from server

typedef enum
{
	STATUS_NONE,
	STATUS_QUERY_CONNECTION_STATUS,
	STATUS_WIFI_RESTART,
	STATUS_ECHO_OFF,
	STATUS_SET_RFPOWER,
	STATUS_DISABLE_SLEEP_MODE,
	STATUS_CHECK_WIFI_MODE,
	STATUS_GET_WIFI_MODE,
	STATUS_SET_WIFI_MODE,
	STATUS_DELETE_IP_PORT_WITH_DATA,
	STATUS_CONNECT_WIFI,
	STATUS_SET_DHCP,
	STATUS_QUERY_DHCP_INFO,
	STATUS_GET_DHCP_INFO,
	STATUS_QUERY_AP_INFO,
	STATUS_GET_AP_INFO,
	STATUS_SET_LOCAL_INFO,
	STATUS_QUERY_LOCAL_INFO,
	STATUS_GET_LOCAL_INFO,
	STATUS_DISCONNECT_WIFI,
	STATUS_TCP_CONNECT,
	STATUS_SET_TRANSMISSION_MODE,
	STATUS_SET_SEND_DATA_LENGTH,
	STATUS_SEND_DATA,
	STATUS_QUERY_MAC_INFO,
	STATUS_GET_MAC_INFO,
	STATUS_SET_MAC_INFO,
	STATUS_RECEIVE_DATA,
	STATUS_REFUSE_DATA,
	STATUS_TCP_DISCONNECT,
	STATUS_MQTT_USER_CFG,
	STATUS_MQTT_CLIENT_ID,
	STATUS_MQTT_USER_NAME,
	STATUS_MQTT_PASSWORD,
	STATUS_MQTT_CONNECT_CFG,
	STATUS_MQTT_QUERY_CONNECT_STATE,
	STATUS_MQTT_GET_CONNECT_STATE,
	STATUS_MQTT_CONNECT,
	STATUS_MQTT_PUB_STR,
	STATUS_MQTT_PUB_BIN,
	STATUS_MQTT_SUB,
	STATUS_MQTT_UNSUB,
	STATUS_MQTT_DISCONNECT,

	STATUS_MAX
}NetworkStatus;

typedef struct _NetworkInfoData {
	rt_uint8_t response;
	NetworkStatus networkStatus;

	rt_uint8_t data[64];
} NetworkInfoData;

rt_bool_t InitNetworkManager(void);
void DeInitNetworkManager(void);
void NetworkMangerSendMessage(MqData_t *pMqData);
rt_bool_t StartNetworkManager(void);
void SendData(rt_uint8_t *pData, rt_size_t dataSize);

#endif /* NETWORK_NETWORKMANAGER_H_ */
