iiot_server:
  tcp_server:
    ip_address: 'localhost'
    port: 1233

  redis_server:
    ip_address: 'localhost'
    port: 6379
    pwd: ''

  rabbit_mq:
    ip_address: 'localhost'
    port: 5672
    id: ''
    pwd: ''
    exchange: ''
    exchange_type: ''

  mongodb:
    ip_address: 'localhost'
    port: 27017
    id: ''
    pwd: ''
    db: ''

  influxdb:
    ip_address: 'localhost'
    port: 8086
    id: ''
    pwd: ''
    db: ''